---
# tasks file for virtio-win

- name: Install vdagent and virtio drivers
  block:
    # Include variables and define mandatory variables
    - name: Include OS-specific variables
      include_vars: "{{ ansible_distribution }}.yml"

    - import_tasks: virtio-win.yml
    - import_tasks: vdagent-win.yml
  rescue:
    - name: Print when errors
      ansible.builtin.debug:
        msg: "I caught an error..."
  when: ansible_os_family == "Windows"
